SHELL_FOLDER="$(cd "$(dirname "$0")";pwd)";
PROJECT_FOLDER="$(cd $SHELL_FOLDER; cd ../../; pwd)";

IMAGE_NAME="PROD_IMAGE_NAME_PLACEHOLDER";
TAGD_PROJECT_NAME="REGISTRY/PROD_IMAGE_NAME_PLACEHOLDER";

docker rmi -f $IMAGE_NAME;
docker rmi -f $IMAGE_NAME $TAGD_PROJECT_NAME;
docker build -t $IMAGE_NAME .;
docker tag $IMAGE_NAME "$TAGD_PROJECT_NAME:latest";
docker push $TAGD_PROJECT_NAME;